### ISSUE TITLE
求指导：关于橡皮功能和opengl的一些使用问题。（已经得到邮件回复还会更新，谢谢作者）

### ISSUE THREAD

**Issue by ouyangsimon** [lmf12/GLPaintView#1]
非常感谢作者的分享，非常稀少的openGLES demo。
1.从代码来看，橡皮功能是把画笔颜色设置成背景色，我的画板有需求需要画板背景。这种情况需要把glpaintview设置成透明色，如此该如何完成橡皮功能呢。
2.我有个蓝牙硬件画板，保存着离线笔记的point，可否不打开GLPaintView，直接代码生成图片呢。小白望指教。非常感谢

**Comment by lmf12** [comment]
已更新接口，有 bug 随时反馈。
